# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Johan Kok Zhi Kang
title: Data Scientist & Incoming PhD graduate
email: johan.kok@u.nus.edu
website: https://www.JKOK005.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: jkok005
github_username:  JKOK005
linkedin_username: johan-zhi-kang-kok-582417104

# Additional icon links
additional_links:
- title: medium
  icon: fas fa-camera
  url: https://medium.com/@johankok

about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello world, my name is Johan Kok. I am a Data Scientist with Grab and a full time PhD student with the National University of Singapore.
  
  I have a wealth of experience architecting big data stacks. I have developed fast pipelines and state-of-the-art machine learning models.
  I have also published papers in top CS conferences and have filed 1 patent.

  My personal interest is to explore how we can translate cutting edge research work into real world impact. Research is often orthogonal to what the industry needs and I hope to contribute in bridging this gap. 

  I am proficient in: <mark>Python</mark>, <mark>Scala</mark>, <mark>Java</mark>, <mark>GoLang</mark>

  I am curious about: <mark>Fintech</mark>, <mark>Blockchain</mark>, <mark>Realtime systems design</mark>, <mark>Deep learning</mark>, <mark>Parallel programming</mark>

  I have published papers in: <mark>ACM SIGMOD</mark>, <mark>ACM SIGKDD</mark>, <mark>VLDB</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-left
        title: Crypto Arbitrage Bot
        quote: >
          Low latency trading bot. We did make a fair bit when LUNA crashed lol. 
        description: | # this will include new lines to allow paragraphs
          I collaborated with an ex-JPMorgan senior trader to design a spot-perp arbitrage bot on multiple exchanges.
          
          The bot looks at slippages in prices and executes a trade when the slippage is too large. In theory, this sounds easy but the implementation was a steep challenge.

          I designed and optimized the trading logic so that most trades are profitable. I also built supporting infrastructure to automate the bot's deployment for multiple spot-perp pairs.

      - layout: top-left
        title: AdaptiveStream
        quote: >
          -
        description: | # this will include new lines to allow paragraphs
          -

      - layout: top-left
        title: The Indexed Router
        quote: >
          -
        description: | # this will include new lines to allow paragraphs
          -

      - layout: top-left
        title: Deep Dynamic Graph Partitioning
        quote: >
          -
        description: | # this will include new lines to allow paragraphs
          -

      - layout: top-left
        title: Prestroid
        quote: >
          -
        description: | # this will include new lines to allow paragraphs
          -

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Grab
        link: ??
        # link_text: boringcompany.com
        sub_title: Data Scientist
        caption: Aug 2019 - Present
        quote: >
          -
        description: | # this will include new lines to allow paragraphs
          -

      - layout: left
        title: Grab
        link: ??
        # link_text: boringcompany.com
        sub_title: Data Engineer
        caption: Jan 2018 - July 2019
        quote: >
          -
        description: | # this will include new lines to allow paragraphs
          -

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a 

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
