# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Johan Kok
title: Website (still building)
email: johan.kok@u.nus.edu
website: https://JKOK005.github.io

# Dark Mode (true/false/never)
darkmode: true

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
